project:
  type: website

website:
  google-analytics: "UA-161578393-1"
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/muellerzr
      - icon: twitter
        href: https://twitter.com/TheZachMueller
format:
  html:
    theme: cosmo
    css: styles.css
    embed-resources: true



